In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")

In [3]:
!pip install joblib


You should consider upgrading via the 'C:\Users\nitin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [4]:
import joblib

In [76]:
class Perceptron:
    def __init__(self ,eta: float=None,epochs:int=None):
        self.weight=np.random.randn(3)*1e-4
        self.eta=eta  #learning rate
        self.epochs=epochs
    def __z_outcome(self,inputs,weight):
        return np.dot(inputs,weight)
    def activation_fun(self,z):
        return np.where(z>0,1,0)
    def fit(self,X,y):
        self.X=X
        self.y=y
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"x_with_bias: \n{X_with_bias}")
        for epoch in range(self.epochs):
            print(epoch)
            z=self.__z_outcome(X_with_bias,self.weight)
            print("z",z)
            yhat=self.activation_fun(z)
            print("predicted",yhat)
            self.error=self.y-yhat
            self.weight=self.weight+self.eta*np.dot(X_with_bias.T,self.error)
            print("weight",self.weight)           
    def predict(self,X):
        X_with_bias=np.c_[X,-np.ones((len(X),1))]
        z=self.__z_outcome(X_with_bias,self.weight)
        return self.activation_fun(z)
        

In [77]:
x=np.ones((4,2))
x
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [78]:
obj=Perceptron()

In [85]:
obj.fit(x,y)

x_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


TypeError: 'NoneType' object cannot be interpreted as an integer

In [80]:
OR={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

In [81]:
pd_or=pd.DataFrame(OR)

In [82]:
pd_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [83]:
def prepare_data(df,target="y"):
    X=df.drop(target,axis=1)
    y=df[target]
    return X,y

In [84]:
X,y=prepare_data(pd_or)
model=Perceptron(0.1,10)

In [63]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [64]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [86]:
model.fit(X,y)

x_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
0
z [8.24262713e-05 1.50171030e-04 4.88067300e-05 1.16551488e-04]
predicted [1 1 1 1]
weight [-3.36195413e-05  6.77447583e-05  9.99175737e-02]
1
z [-0.09991757 -0.09984983 -0.09995119 -0.09988345]
predicted [0 0 0 0]
weight [ 0.19996638  0.20006774 -0.20008243]
2
z [0.20008243 0.40015017 0.40004881 0.60011655]
predicted [1 1 1 1]
weight [ 0.19996638  0.20006774 -0.10008243]
3
z [0.10008243 0.30015017 0.30004881 0.50011655]
predicted [1 1 1 1]
weight [ 1.99966380e-01  2.00067745e-01 -8.24262713e-05]
4
z [8.24262713e-05 2.00150171e-01 2.00048807e-01 4.00116551e-01]
predicted [1 1 1 1]
weight [0.19996638 0.20006774 0.09991757]
5
z [-0.09991757  0.10015017  0.10004881  0.30011655]
predicted [0 1 1 1]
weight [0.19996638 0.20006774 0.09991757]
6
z [-0.09991757  0.10015017  0.10004881  0.30011655]
predicted [0 1 1 1]
weight [0.19996638 0.20006774 0.09991757]
7
z [-0.09991757  0.10015017  0.10004881  0.30011655]
predict

In [66]:
model.predict(X)

array([0, 1, 1, 1])

In [70]:
model.predict(X=[[-20,1]])

array([0])