In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

In [114]:
class Perceptron:
    def __init__(self,eta: float=None, epochs :int=None ):
        self.eta=eta
        self.epochs=epochs
        self.weight=np.random.randn(3)*1e-4
    def _z_outcome(self,input1,weight):
        return np.dot(input1,self.weight)
    def activation_fun(self,z):
        return np.where(z>0,1,0)
    def fit(self,X,y):
        self.X=X
        self.y=y
        X_with_biased=np.c_[self.X,-np.ones((len(self.X),1))]
        print("X_with_biased",X_with_biased)
        for epoch in range(self.epochs):
            z=self._z_outcome(X_with_biased,self.weight)
            y_hat=self.activation_fun(z)
            print("predict",y_hat)
            self.error=self.y-y_hat
            print("error",self.error)
            self.weight=self.weight+self.eta*np.dot(X_with_biased.T,self.error)
            print("weight",self.weight)
    def predict(self,X):
        X_with_biased=np.c_[X,-np.ones((len(X),1))]
        z=self._z_outcome(X_with_biased,self.weight)
        return self.activation_fun(z)
            
            

In [115]:
np.random.randn(3)*1e-4

array([ 1.31774074e-04, -2.86531871e-05,  3.92239946e-05])

In [116]:
model=Perceptron(0.1,10)

In [117]:
X=np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
X
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [119]:
model.fit(X,y)

X_with_biased [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
predict [1 1 1 1]
error [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [120]:
OR={
    "x1":[0,0,1,1]
    ,"x2":[0,1,0,1],
    "y":[0,1,1,1]
}

In [121]:
pd_or=pd.DataFrame(OR)
pd_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [122]:
def data_prepare(pd_or,target="y"):
    X=pd_or.drop(target,axis=1)
    y=pd_or[target]
    return X,y

In [123]:
X,y=data_prepare(pd_or)

In [124]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [125]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [126]:
model.fit(X,y)

X_with_biased [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
predict [1 1 1 1]
error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
weight [-9.98090380e-06 -7.63477695e-05  9.98997384e-02]
predict [0 0 0 0]
error 0    0
1    1
2    1
3    1
Name: y, dtype: int64
weight [ 0.19999002  0.19992365 -0.20010026]
predict [1 1 1 1]
error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
weight [ 0.19999002  0.19992365 -0.10010026]
predict [1 1 1 1]
error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
weight [ 1.99990019e-01  1.99923652e-01 -1.00261556e-04]
predict [1 1 1 1]
error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
weight [0.19999002 0.19992365 0.09989974]
predict [0 1 1 1]
error 0    0
1    0
2    0
3    0
Name: y, dtype: int64
weight [0.19999002 0.19992365 0.09989974]
predict [0 1 1 1]
error 0    0
1    0
2    0
3    0
Name: y, dtype: int64
weight [0.19999002 0.19992365 0.09989974]
predict [0 1 1 1]
error 0    0
1    0
2    0
3    0
Name: y, dtype: int64
wei

In [127]:
model.predict(X)

array([0, 1, 1, 1])

In [130]:
c=[[1,0]]

In [133]:
model.predict(X=[[0,0]])

array([0])