In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")

In [3]:
!pip install joblib


You should consider upgrading via the 'C:\Users\nitin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [4]:
import joblib

In [20]:
class Perceptron:
    def __init__(self ,eta: float=None,epochs:int=None):
        self.weight=np.random.randn(3)*1e-4
        self.eta=eta  #learning rate
        self.epochs=epochs
    def fit(self,X,y):
        self.X=X
        self.y=y
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"x_with_bias: \n{X_with_bias}")

In [21]:
x=np.ones((4,2))
x
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [22]:
obj=Perceptron()

In [23]:
obj.fit(x,y)

x_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
